### ISSUE TITLE
Error "Something went wrong in 'filename.txt' "When viewing history

### ISSUE THREAD

**Issue by hosadokha** [Pike96/UHistory#3]
After trying it for a while, I discovered that It cant Read the history if the files backed up are from more than one browser and there is a overlap in dates, **Even if I gave it a different filename**  ..It gives me error "something went wrong in "filename".txt " 
I think that would easily be solved if I was able to save the file backups in another folder in gdrive (for each browser), and when I want to read I should be able to choose which folder I want..

**Comment by Pike96** [comment]
Sorry for the late reply. I rewrote the entire project.
You can now add a tag or change folder name to read / backup your history files. So this extension can read all histories under your selected folder on any device.
